# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: # Rapid Analysis
            image: true
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
    footer:
        content:
            logo:
                text: # Rapid Analysis
                image: true
            copyright: Copyright &copy; 2023. - Weburban <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: 'https://www.facebook.com/weburban'
            - network_name: twitter
              profile_url: 'https://twitter.com/weburban'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/@weburban'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
